version: '3'

services:
  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql/
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - cf-net
      
  redisdb:
    container_name: redis
    hostname: redisdb
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - cf-net
    depends_on:
      - db
      
  django:
    container_name: django
    hostname: django
    build: .
    command: gunicorn cloud_finance.wsgi:application --workers 5 --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: /entrypoint.sh
    links: 
      - "db:database"
    depends_on:
      - db
      - redisdb
    networks:
      - cf-net
      
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - cf-net
    depends_on:
      - django
      - db
      - redisdb

  celery:
    container_name: celery
    build: .
    command: celery worker -A cloud_finance -l info --autoscale=10,5
    volumes:
      - .:/code
    env_file: 
      - .env
    links: 
      - "db:database"
    networks:
      - cf-net
    depends_on:
      - db
      - redisdb
      - django

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery beat -A cloud_finance --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    volumes:
      - .:/code
    env_file: 
      - .env
    links: 
      - "db:database"
    networks:
      - cf-net
    depends_on:
      - db
      - redisdb
      - django

volumes: 
  mariadb-data:
networks:
  cf-net:
